package com.thesystem.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * A single learning session log entry.
 *
 * Tracks YouTube videos, articles, DevMastery topics, and any other learning activity.
 * Includes AI-extracted notebook data (Gemini Smart Notebook) and SM-2 spaced repetition state.
 *
 * XP Formula:
 *   Base:     durationMinutes / 5
 *   +10 if noteTaken
 *   +15 if codedAlong
 *   +20 if recallDone (same session or within 24 hrs)
 *   ×0.8 / ×1.0 / ×1.2 quality multiplier (confidence 1-2 / 3 / 4-5)
 *   Min: 5 XP, Max: 100 XP per session
 */
@Entity
@Table(name = "learning_logs")
@Getter
@Setter
public class LearningLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "player_id", nullable = false)
    private Long playerId;

    @Column(name = "log_date", nullable = false)
    private LocalDate logDate = LocalDate.now();

    // ── WHAT ──────────────────────────────────────────────────────────────────

    /** Broad subject area: "Java", "Spring Boot", "DSA", "System Design", "Angular", etc. */
    @Column(nullable = false, length = 100)
    private String subject;

    /** Specific topic: "OOP — Inheritance", "HashMap Internal Working", "Binary Search" */
    @Column(nullable = false, length = 255)
    private String topic;

    // ── WHERE ─────────────────────────────────────────────────────────────────

    /** Source enum: YOUTUBE, DEVMASTERY, WEBSITE, BOOK, PLATFORM, OTHER */
    @Column(nullable = false, length = 30)
    private String source = "YOUTUBE";

    /** YouTube URL, article link, etc. (nullable) */
    @Column(name = "source_url", length = 500)
    private String sourceUrl;

    /** Human-readable platform: "Concept & Coding", "Baeldung", "DevMastery" */
    @Column(name = "platform_name", length = 100)
    private String platformName;

    // ── HOW LONG ──────────────────────────────────────────────────────────────

    @Column(name = "duration_minutes", nullable = false)
    private int durationMinutes = 30;

    // ── ACTIVITY TYPE ─────────────────────────────────────────────────────────

    /** WATCHED_VIDEO, READ_ARTICLE, CODED_ALONG, PRACTICED, TOOK_NOTES */
    @Column(name = "activity_type", length = 30)
    private String activityType = "WATCHED_VIDEO";

    @Column(name = "note_taken")
    private boolean noteTaken = false;

    @Column(name = "coded_along")
    private boolean codedAlong = false;

    // ── RECALL / SPACED REPETITION ────────────────────────────────────────────

    /** Whether the hunter completed a self-recall/Feynman check for this session. */
    @Column(name = "recall_done")
    private boolean recallDone = false;

    /** Self-assessed confidence after recall: 1 (forgot) to 5 (perfect). */
    @Column(name = "confidence_score")
    private int confidenceScore = 0;

    /** SM-2 next review date. Set on log creation (logDate+1), updated on each recall. */
    @Column(name = "review_due_date")
    private LocalDate reviewDueDate;

    /** How many times the hunter has recalled this session. */
    @Column(name = "review_count")
    private int reviewCount = 0;

    // ── XP ────────────────────────────────────────────────────────────────────

    @Column(name = "xp_earned")
    private int xpEarned = 0;

    // ── AI SMART NOTEBOOK (Gemini) ─────────────────────────────────────────────

    /** Video title extracted by Gemini (or manually entered). */
    @Column(name = "video_title", length = 300)
    private String videoTitle;

    /** 3-4 sentence plain-English summary generated by Gemini. */
    @Column(name = "ai_summary", length = 2000)
    private String aiSummary;

    /**
     * JSON array of 5-8 key concepts IN ORDER as taught in the video.
     * Example: ["1. Inheritance allows child to reuse parent methods", "2. super() calls parent constructor", ...]
     */
    @Column(name = "ai_key_points", length = 3000)
    private String aiKeyPoints;

    /**
     * JSON array of 5 recall questions generated by Gemini.
     * Example: ["What is the difference between extends and implements?", ...]
     */
    @Column(name = "ai_recall_questions", length = 2000)
    private String aiRecallQuestions;

    /**
     * JSON array tracking which key points were remembered during recall.
     * Example: [true, true, false, true, false]
     * Updated by markRecallDone.
     */
    @Column(name = "recall_key_point_results", length = 500)
    private String recallKeyPointResults;

    /** true once Gemini has processed the sourceUrl and filled ai* fields. */
    @Column(name = "ai_analyzed")
    private boolean aiAnalyzed = false;

    // ── DEVMASTERY LINK ───────────────────────────────────────────────────────

    /** UUID of the DevMastery topic (nullable — only set for DevMastery-sourced logs). */
    @Column(name = "devmastery_topic_id", length = 36)
    private String devMasteryTopicId;

    // ── NOTES ─────────────────────────────────────────────────────────────────

    @Column(length = 1000)
    private String notes;

    @Column(name = "created_at")
    private LocalDateTime createdAt = LocalDateTime.now();
}
